server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=MyShopDB;encrypt=true;trustServerCertificate=true;
    username: SA
    password: Thien?1010
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
api:
  prefix: api/v1/shop-app

jwt:
  expiration: 2592000
  securityKey: Dm2Atabz2nObWsHxeeoIBZnqC8lWTYLFoMC/Hr3E7s4=