server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=MyShopDB;encrypt=true;trustServerCertificate=true;
    username: SA
    password: Thien?1010
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  redis:
    host: localhost
    port: 6379

api:
  prefix: api/v1/shop-app

jwt:
  expiration: 2592000
  securityKey: Dm2Atabz2nObWsHxeeoIBZnqC8lWTYLFoMC/Hr3E7s4=

openapi:
  service:
    api-docs: backend-service
    server: http://localhost:${server.port}/${api.prefix}
    title: Backend service
    version: 1.0.0


logging:
  level:
    root: INFO
    com.CIC.shop_app_backend: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: logs/application.log
    max-size: 10MB
    max-history: 30